baseURL: https://hannah-blackburn.netlify.app/
languageCode: en-US
title: Hannah Blackburn
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
permalinks:
  post: /:year/:month/:day/:slug
params:
  author: Hannah Blackburn
  avatar: img/profile.png
  custom_css: []
  custom_js: []
  description: Hannah Blackburn is the unofficial psychologist. 
  social:
    Email: unofficialpsychologist@gmail.com
    Github: unofficialpsychologist
    Twitter: "@hannah_h_b"
menu:
  main:
    - identifier: blog
      name: blog
      url: /blog/
      weight: 1
    - identifier: about
      name: about
      url: /about/
      weight: 2
    - identifier: resume
      name: resume
      url: /resume/
      weight: 3
